### ISSUE TITLE
运行main.py后进程停在这不动了

### ISSUE THREAD

**Issue by hakyeong** [nyaoouo/FFDraw#21]
进程停在 [2023-05-31 13:25:05,411]       [WARNING]       [InjectHandler] server fail, res:ffffffff  这一步
截图一直上传不上来（）

**Comment by nyaoouo** [comment]
![image](https://github.com/nyaoouo/FFDraw/assets/64143453/21d8f064-71ba-497d-ba74-48a9b9c47e6a)
删除这俩dll重启试试

**Comment by hakyeong** [comment]
> ![image](https://user-images.githubusercontent.com/64143453/242175155-21d8f064-71ba-497d-ba74-48a9b9c47e6a.png) 删除这俩dll重启试试

还是不行qaq

**Comment by nyaoouo** [comment]
重启关防毒之类都试试，我也不知道为啥会这样，我这边无法复现这个问题（摊手

**Comment by hakyeong** [comment]
> 重启关防毒之类都试试，我也不知道为啥会这样，我这边无法复现这个问题（摊手

看来是无缘了555

**Comment by hakyeong** [comment]
> 看看梯子有没有开，有个人是开了梯子这个问题解决了，不一定有用但是至少检查一下试一下

梯子一直是开着的

**Comment by hakyeong** [comment]
用了白痴一键包解决了
