### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by 2419119384** [nyaoouo/FFDraw#22]
Requirement already satisfied: pip in c:\users\pxzrs\desktop\ffd\ffdraw\venv\lib\site-packages (22.3.1)
WARNING: The repository located at pypi.tuna.tsinghua.edu.cn is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.tuna.tsinghua.edu.cn'.
WARNING: The repository located at pypi.tuna.tsinghua.edu.cn is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.tuna.tsinghua.edu.cn'.
WARNING: There was an error checking the latest version of pip.
Looking in indexes: http://pypi.tuna.tsinghua.edu.cn/simple
WARNING: The repository located at pypi.tuna.tsinghua.edu.cn is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.tuna.tsinghua.edu.cn'.
ERROR: Could not find a version that satisfies the requirement glfw~=2.5.3 (from versions: none)
ERROR: No matching distribution found for glfw~=2.5.3
WARNING: The repository located at pypi.tuna.tsinghua.edu.cn is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.tuna.tsinghua.edu.cn'.
WARNING: There was an error checking the latest version of pip.

**Comment by 2419119384** [comment]
后面还有一个
ModuleNotFoundError: No module named 'win32con'

**Comment by nyaoouo** [comment]
懒人包内容请前往对应repo提issue
