### ISSUE TITLE
用的白痴一键包 提示下的那个git exe无法运行

### ISSUE THREAD

**Issue by Brsbot233** [nyaoouo/FFDraw#29]
![image](https://github.com/nyaoouo/FFDraw/assets/113752140/660ccf57-76b9-4825-b195-69c6bea234b7)
![image](https://github.com/nyaoouo/FFDraw/assets/113752140/6ee19624-038e-4b8d-862c-fb4a00658ec4)

**Comment by Brsbot233** [comment]
py版本安装环境好像成功了但是运行有报错不知道为什么
![image](https://github.com/nyaoouo/FFDraw/assets/113752140/1c3a31ed-eebf-455a-be2d-eaf2554bc781)
![image](https://github.com/nyaoouo/FFDraw/assets/113752140/f8c21033-2ca8-417c-a164-a40d6c3f4e59)
![image](https://github.com/nyaoouo/FFDraw/assets/113752140/fb480922-79c9-4e61-8686-36e2eb6e46fa)

**Comment by gogofishman** [comment]
updata是程序内的更新问题，用了傻瓜包可以直接忽略

**Comment by nyaoouo** [comment]
一键包内容请前往对应repo提问
