### ISSUE TITLE
安装后无法运行

### ISSUE THREAD

**Issue by Kitterato** [nyaoouo/FFDraw#33]
Active code page: 65001
Python3.11运行正常！
git version 2.40.1.windows.1
git-2.40.1运行正常！

http\https网络代理：127.0.0.1:10808

正在从远程仓库更新
D:\FFD\FFDraw
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

更新完成！

已进入venv虚拟环境

正在检查并安装pip环境包
Requirement already satisfied: pip in d:\ffd\ffdraw\venv\lib\site-packages (23.1.2)
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

pip环境包更新完成

正在启动...
C:\Users\K.K\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'D:\\FFD\\FFDraw\\main_cn.py': [Errno 2] No such file or directory
Press any key to continue . . .

按键后窗口关闭且无任何反应

**Comment by Kitterato** [comment]
删除重装后一直提示无法链接github，梯子是v2ray端口也改成了10808。浏览器能正常访问github

**Comment by nyaoouo** [comment]
一键脚本问题请优先找脚本作者处理
