### ISSUE TITLE
请问，这个是啥情况。

### ISSUE THREAD

**Issue by OukaNagisa** [nyaoouo/FFDraw#35]
![image](https://github.com/nyaoouo/FFDraw/assets/137282999/c7a37ba4-23c4-4fc8-b7e2-22d5098e3854)

**Comment by CNwty** [comment]
我最开始也碰到了  后面发现是Python版本的问题 他创建虚拟环境的时候用的是你系统环境 确定全局的Python环境是3.10以上就行

**Comment by nyaoouo** [comment]
一键脚本问题请优先找脚本作者处理，这里是submodule 没有update
