### ISSUE TITLE
懒人包运行完run_cn.bat之后报错 FileNotFoundError: [WinError 2] 系统找不到指定文件

### ISSUE THREAD

**Issue by hakyeong** [nyaoouo/FFDraw#38]
![image](https://github.com/nyaoouo/FFDraw/assets/21173506/de89bb65-5582-4203-96c1-88a1db92bbb4)
不知道是缺少了什么文件。。

**Comment by fatinghenji** [comment]
如果遇到报错 Npcap/Winpcap is not installed 之类，请下载 [npcap](https://npcap.com/dist/npcap-1.72.exe) 安装后重启

**Comment by hakyeong** [comment]
> 如果遇到报错 Npcap/Winpcap is not installed 之类，请下载 [npcap](https://npcap.com/dist/npcap-1.72.exe) 安装后重启

好的 感谢！

**Comment by hakyeong** [comment]
> 如果遇到报错 Npcap/Winpcap is not installed 之类，请下载 [npcap](https://npcap.com/dist/npcap-1.72.exe) 安装后重启

草 看了下好像是pvp插件的问题。。
