### ISSUE TITLE
报错:'pattern is not unique, 2 is found, use find_points to deal with this error'

### ISSUE THREAD

**Issue by DirtyManZBY** [nyaoouo/FFDraw#47]
![image](https://github.com/nyaoouo/FFDraw/assets/150209992/9cdbb886-2fb6-4a1a-9ac6-07e0684f8403)
如图，用conda和pycharm配完都报了这个错

**Comment by DirtyManZBY** [comment]
已解决，开启独显就好了

**Comment by nyaoouo** [comment]
实际上是你第一次没更新好第二次才更好……
