### ISSUE TITLE
报错 KeyError: 'pattern is not unique, 2 is found, use find_vals to deal with this error'

### ISSUE THREAD

**Issue by ONBBss** [nyaoouo/FFDraw#50]
我重新下载安装了python 版本ffd，并且重装过游戏，手动更新了NyLib都无法解决。还尝试了readme中的三种安装版本，都无法解决，并且使用ce搜索48 ? ? * * * * 48 ? ? 0f 84 ? ? ? ? 0f ? ? ? ? ? ? 45该特征码后只显示一个结果，但是ffd依旧报错有2个。[相同报错的issues](https://github.com/nyaoouo/FFDraw/issues/47)中提到的切换独显以及更新问题我都有试过，还是无法解决。
![{1C21F3CB-F822-4073-8EF6-B8D727C47C54}](https://github.com/nyaoouo/FFDraw/assets/124436439/5f684c33-9a86-4128-82a9-772a3049b2fa)
![{FA0814D2-0C7F-4713-B84D-E57B4B780CA1}](https://github.com/nyaoouo/FFDraw/assets/124436439/b8dbeac9-fead-46be-8bc9-def60c07d6ea)

**Comment by nyaoouo** [comment]
https://github.com/nyaoouo/FFDraw/commit/cc9c7fdde9e27a1e9beb7135df035dcb8e06cb0a ...
你版本太旧了吧
